package com.csc.intellis.constants;

public enum ElementType {
	TEXTBOX, DATE, SETDATE, TOAST, COPY, PASTE, TAB, DRAG, DROP, ALT0, ALT1, ALT2, ALT3, ALT4, ALT5, ALT6, TOOLTIP, SELECTBOX, BUTTON, SWITCHURL, CHECKUNCHECK, RETURNKEY, DELETEKEY, HOMEKEY, ESCAPEKEY, JHOVER, LINK, JLINK, UPLOAD, SAVE, SAVECANCEL, ELEMENTNOTPRESENT, HOVER, TEXTAREA, CHECKBOX, RADIOBUTTON, IMAGE, SCROLL, ALERT, ERRMESSAGE, SWITCHTOCHILD, SWITCHTOPARENT, CLOSECHILDWINDOW, CurrMnthDate, NextMnthDate, VERIFY, TABLE, TODAYDATE, TOMORROWDATE, YESTERDAYDATE, NOTVERIFY, TEXTBOXVERIFY, DISABLE, VERIFYENABLED, DYNAMICSELBOX
}